---
# This playbook makes backup of MongoDB database.

- name: Deploy MongoDB
  hosts: all
  gather_facts: yes
  become: yes
  
  collections:
  - sudmed.mongodb

  tasks:
    - import_role:
        name: mongo-backup
